# Generated by Django 5.2.9 on 2026-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_listings_active', models.IntegerField(default=0)),
                ('new_listings', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('adoptions_finalized', models.IntegerField(default=0)),
                ('service_bookings', models.IntegerField(default=0)),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='analytics_p_date_16622d_idx')],
            },
        ),
    ]
