# Generated by Django 5.1.3 on 2025-12-14 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('other', 'Other')], max_length=20)),
                ('own_or_rent', models.CharField(choices=[('own', 'Own'), ('rent', 'Rent')], max_length=10)),
                ('landlord_approval', models.BooleanField(default=False, help_text='Required if renting')),
                ('landlord_document_url', models.URLField(blank=True, null=True)),
                ('yard_type', models.CharField(choices=[('none', 'No Yard'), ('small_unfenced', 'Small Unfenced Yard'), ('small_fenced', 'Small Fenced Yard'), ('medium_unfenced', 'Medium Unfenced Yard'), ('medium_fenced', 'Medium Fenced Yard'), ('large_fenced', 'Large Fenced Yard'), ('acreage', 'Acreage')], max_length=20)),
                ('yard_fenced', models.BooleanField(default=False)),
                ('num_adults', models.IntegerField(default=1)),
                ('num_children', models.IntegerField(default=0)),
                ('children_ages', models.JSONField(default=list, help_text="List of children's ages")),
                ('current_pets', models.JSONField(default=list)),
                ('pet_experience', models.JSONField(default=dict)),
                ('ever_surrendered_pet', models.BooleanField(default=False)),
                ('surrender_explanation', models.TextField(blank=True, help_text='If yes, explain what happened')),
                ('work_schedule', models.CharField(help_text="e.g., '9-5 weekdays', 'work from home'", max_length=100)),
                ('activity_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='1=Sedentary, 5=Very Active')),
                ('exercise_commitment_hours', models.DecimalField(decimal_places=1, help_text='Hours per day willing to dedicate to pet exercise', max_digits=3)),
                ('travel_frequency', models.CharField(choices=[('rarely', 'Rarely'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('frequently', 'Frequently')], max_length=20)),
                ('references', models.JSONField(default=list, help_text='Personal references (2 required)')),
                ('vet_reference_clinic', models.CharField(blank=True, max_length=200)),
                ('vet_reference_phone', models.CharField(blank=True, max_length=15)),
                ('why_adopt', models.TextField(help_text='Why do you want to adopt a pet? (500+ words)')),
                ('ideal_pet_description', models.TextField(blank=True, help_text='Describe your ideal pet (optional)')),
                ('readiness_score', models.IntegerField(default=0, help_text='Calculated based on profile completeness and suitability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adopter Profile',
                'verbose_name_plural': 'Adopter Profiles',
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Why do you want to adopt this specific pet? (500+ words)')),
                ('custom_answers', models.JSONField(blank=True, default=dict, help_text="Answers to pet owner's custom questions")),
                ('readiness_score', models.IntegerField(default=0, help_text='Calculated from adopter profile (0-100)')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('info_requested', 'Info Requested'), ('rejected', 'Rejected'), ('approved_meet_greet', 'Approved for Meet & Greet'), ('meet_greet_success', 'Meet & Greet Success'), ('trial_period', 'Trial Period'), ('adopted', 'Adopted'), ('completed', 'Completed'), ('returned', 'Returned')], default='pending_review', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('owner_notes', models.TextField(blank=True, help_text='Internal notes for the pet owner', null=True)),
                ('info_requested_at', models.DateTimeField(blank=True, null=True)),
                ('info_request_message', models.TextField(blank=True, help_text='Questions from pet owner requesting more info')),
                ('contact_info_revealed_at', models.DateTimeField(blank=True, help_text='When contact info was revealed after meet & greet approval', null=True)),
                ('trial_period_start', models.DateTimeField(blank=True, null=True)),
                ('trial_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_period_duration', models.IntegerField(default=30, help_text='Trial period duration in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adoption Application',
                'verbose_name_plural': 'Adoption Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='Scheduled date and time for home check')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('passed', 'Passed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('checklist_results', models.JSONField(blank=True, default=dict, help_text='Structured results from home check criteria')),
                ('overall_score', models.IntegerField(blank=True, help_text='Overall score 0-100', null=True)),
                ('passed', models.BooleanField(blank=True, help_text='Did the home check pass?', null=True)),
                ('notes', models.TextField(blank=True, help_text='Detailed notes from the visit')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Optional photos from the visit (URLs)')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvements or next steps')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Check',
                'verbose_name_plural': 'Home Checks',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='MeetGreetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='Date and time of meet & greet')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Expected duration in minutes')),
                ('location_type', models.CharField(choices=[('owner_home', "Pet Owner's Home"), ('public_place', 'Public Place'), ('adopter_home', "Adopter's Home"), ('other', 'Other')], default='public_place', max_length=20)),
                ('location_details', models.TextField(help_text='Detailed address or location description')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('confirmed_by_owner', models.BooleanField(default=False)),
                ('confirmed_by_adopter', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Successful - Proceed to Next Step'), ('concerns', 'Some Concerns - Needs Discussion'), ('not_a_match', 'Not a Good Match')], max_length=20)),
                ('owner_notes', models.TextField(blank=True, help_text="Pet owner's notes from the meeting")),
                ('adopter_notes', models.TextField(blank=True, help_text="Adopter's notes from the meeting")),
                ('reminder_sent_to_owner', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_to_adopter', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meet & Greet Schedule',
                'verbose_name_plural': 'Meet & Greet Schedules',
                'ordering': ['scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='VisitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('meet_greet', 'Meet & Greet'), ('home_check', 'Home Check'), ('follow_up', 'Follow-up Visit'), ('trial_period', 'Trial Period Check-in'), ('final_handoff', 'Final Pet Handoff'), ('other', 'Other')], max_length=20)),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(help_text='Detailed notes from the visit')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='URLs to any attached documents or photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visit Note',
                'verbose_name_plural': 'Visit Notes',
                'ordering': ['-visit_date'],
            },
        ),
    ]
