# Generated by Django 5.1.3 on 2025-12-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adopterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='adopter_profile',
            field=models.ForeignKey(blank=True, help_text='Snapshot of adopter profile at time of application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='adoption.adopterprofile'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pets.rehominglisting'),
        ),
        migrations.AddField(
            model_name='homecheck',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_checks', to='adoption.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='homecheck',
            name='performed_by',
            field=models.ForeignKey(help_text='Admin, volunteer, or pet owner performing the check', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_checks_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetgreetschedule',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_greet_schedules', to='adoption.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_notes', to='adoption.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='visitnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='adopterprofile',
            constraint=models.CheckConstraint(condition=models.Q(('readiness_score__gte', 0), ('readiness_score__lte', 100)), name='readiness_score_range'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['status', '-created_at'], name='adoption_ad_status_2c624c_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['applicant', 'status'], name='adoption_ad_applica_472110_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['pet', 'status'], name='adoption_ad_pet_id_c9ddbf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionapplication',
            unique_together={('applicant', 'pet')},
        ),
    ]
