# Generated by Django 5.2.9 on 2026-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('post_reaction', 'Post Reaction'), ('post_comment', 'Post Comment'), ('comment_reply', 'Comment Reply'), ('message_received', 'Message Received'), ('application_submitted', 'Application Submitted'), ('application_update', 'Application Update'), ('adoption_finalized', 'Adoption Finalized'), ('review_received', 'Review Received'), ('group_invitation', 'Group Invitation'), ('event_reminder', 'Event Reminder'), ('lost_pet_alert', 'Lost Pet Alert'), ('system_announcement', 'System Announcement')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('related_object_id', models.PositiveIntegerField(null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='in_app', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
