# Generated by Django 5.2.9 on 2026-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('event_type', models.CharField(choices=[('playdate', 'Playdate'), ('meetup', 'Meetup'), ('charity', 'Charity'), ('training', 'Training'), ('other', 'Other')], max_length=50)),
                ('location_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location_address', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('cover_photo_url', models.URLField(blank=True, null=True)),
                ('rsvp_count', models.IntegerField(default=0)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('going', 'Going'), ('maybe', 'Maybe'), ('not_going', 'Not Going')], default='going', max_length=20)),
                ('num_guests', models.IntegerField(default=0)),
                ('rsvp_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('group_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('official', 'Official')], default='public', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('species', 'Species Specific'), ('location', 'Location Based'), ('interest', 'Interest Based'), ('support', 'Support'), ('other', 'Other')], max_length=50, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='groups/covers/')),
                ('cover_photo_url', models.URLField(blank=True, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_state', models.CharField(blank=True, max_length=50, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('member_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('banned', 'Banned')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('duration_days', models.IntegerField(default=7)),
                ('expires_at', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('total_votes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('vote_count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=5000)),
                ('post_type', models.CharField(choices=[('standard', 'Standard'), ('question', 'Question'), ('story', 'Story'), ('poll', 'Poll'), ('event', 'Event'), ('lost_pet', 'Lost Pet'), ('success_story', 'Success Story')], default='standard', max_length=20)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('privacy_level', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('group_only', 'Group Members Only'), ('private', 'Private')], default='public', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('care', 'Care'), ('wow', 'Wow'), ('sad', 'Sad'), ('funny', 'Funny')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
