# Generated by Django 5.1.3 on 2025-12-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FosterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1, help_text='Maximum number of animals')),
                ('current_count', models.IntegerField(default=0, help_text='Current number of animals in care')),
                ('current_availability', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('full', 'Full')], default='available', max_length=20)),
                ('species_accepted', models.JSONField(default=list, help_text='List of species accepted')),
                ('environment_details', models.JSONField(default=dict, help_text='Detailed environment information')),
                ('care_standards', models.JSONField(default=dict, help_text='Care standards and routines')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Daily rate in USD', max_digits=6)),
                ('weekly_discount', models.IntegerField(default=0, help_text='Percentage discount for weekly booking (0-100)')),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='Monthly rate in USD', max_digits=6)),
                ('photos', models.JSONField(default=list, help_text='Array of photo URLs (8+ photos required)')),
                ('video_url', models.URLField(blank=True, help_text='Optional facility tour video URL', null=True)),
            ],
            options={
                'verbose_name': 'Foster Service',
                'verbose_name_plural': 'Foster Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('vet', 'Veterinarian'), ('foster', 'Foster Home'), ('trainer', 'Trainer'), ('walker', 'Pet Walker'), ('groomer', 'Groomer'), ('sitter', 'Pet Sitter')], max_length=20)),
                ('description', models.TextField(help_text='Business description (500+ words required)')),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('license_number', models.CharField(blank=True, help_text='Professional license number', max_length=50)),
                ('insurance_info', models.TextField(blank=True, help_text='Insurance details')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('photos', models.JSONField(default=list, help_text='Array of photo URLs (business photos)')),
                ('services_offered', models.JSONField(default=list, help_text='List of services offered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_overall', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('rating_communication', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('rating_cleanliness', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('rating_quality', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Quality of Care')),
                ('rating_value', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], verbose_name='Value for Money')),
                ('review_text', models.TextField(help_text='Detailed review (200+ words required)')),
                ('photo_url', models.URLField(blank=True, help_text='Optional photo with review', null=True)),
                ('service_type', models.CharField(help_text='Type of service used (foster, vet, etc.)', max_length=20)),
                ('verified_client', models.BooleanField(default=False, help_text='Has admin verified this person actually used the service?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializations', models.JSONField(default=list, help_text='List of training specializations')),
                ('primary_method', models.CharField(choices=[('positive_reinforcement', 'Positive Reinforcement'), ('clicker_training', 'Clicker Training'), ('balanced', 'Balanced Training'), ('other', 'Other Methods')], default='positive_reinforcement', max_length=30)),
                ('training_philosophy', models.TextField(help_text='Detailed explanation of training approach and philosophy')),
                ('certifications', models.JSONField(default=list, help_text='List of professional certifications')),
                ('years_experience', models.IntegerField(default=0)),
                ('species_trained', models.JSONField(default=list, help_text='Species the trainer works with (typically dogs, cats)')),
                ('behavioral_issues_addressed', models.JSONField(default=list, help_text='Specific behavioral issues the trainer can address')),
                ('offers_private_sessions', models.BooleanField(default=True)),
                ('offers_group_classes', models.BooleanField(default=False)),
                ('offers_board_and_train', models.BooleanField(default=False)),
                ('offers_virtual_training', models.BooleanField(default=False)),
                ('private_session_rate', models.DecimalField(decimal_places=2, help_text='Hourly rate for private sessions', max_digits=6)),
                ('group_class_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Per-class rate for group sessions', max_digits=6, null=True)),
                ('package_options', models.JSONField(blank=True, default=list, help_text='Pre-packaged training programs with pricing')),
                ('max_clients', models.IntegerField(default=10, help_text='Maximum number of concurrent clients')),
                ('current_client_count', models.IntegerField(default=0)),
                ('accepting_new_clients', models.BooleanField(default=True)),
                ('photos', models.JSONField(default=list, help_text='Photos of trainer with dogs, training sessions, etc.')),
                ('video_url', models.URLField(blank=True, help_text='Promotional video or training demonstration', null=True)),
            ],
            options={
                'verbose_name': 'Trainer Service',
                'verbose_name_plural': 'Trainer Services',
            },
        ),
        migrations.CreateModel(
            name='VeterinaryClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_type', models.CharField(choices=[('general', 'General Practice'), ('emergency', 'Emergency'), ('specialty', 'Specialty'), ('mobile', 'Mobile Vet')], default='general', max_length=20)),
                ('services_offered', models.JSONField(default=list, help_text='List of services offered')),
                ('species_treated', models.JSONField(default=list, help_text='List of species treated')),
                ('hours_of_operation', models.JSONField(default=dict, help_text='Hours for each day of the week')),
                ('pricing_info', models.TextField(help_text='Text description of pricing or specific procedure prices')),
                ('photos', models.JSONField(default=list, help_text='Array of photo URLs (6+ photos required)')),
                ('amenities', models.JSONField(default=list, help_text='List of amenities available')),
                ('emergency_services', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Veterinary Clinic',
                'verbose_name_plural': 'Veterinary Clinics',
            },
        ),
    ]
