# Generated by Django 5.2.9 on 2025-12-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_bookings', to='pets.petprofile'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.fosterservice'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fosterservice',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foster_details', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerservice',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_details', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='veterinaryclinic',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_details', to='services.serviceprovider'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['provider', 'status'], name='services_se_provide_88c639_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['start_date', 'end_date'], name='services_se_start_d_39c499_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['provider_type', 'verification_status'], name='services_se_provide_7674ba_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['city', 'state'], name='services_se_city_4d3971_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['latitude', 'longitude'], name='services_se_latitud_2e2c60_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('provider', 'reviewer')},
        ),
    ]
