# Generated by Django 5.2.9 on 2026-01-19 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
        ('services', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, help_text='Lucide icon name for frontend', max_length=50)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Media',
                'verbose_name_plural': 'Service Media',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.RemoveIndex(
            model_name='serviceprovider',
            name='services_se_provide_7674ba_idx',
        ),
        migrations.RemoveField(
            model_name='fosterservice',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='daily_rate',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='provider_type',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='services_offered',
        ),
        migrations.RemoveField(
            model_name='servicereview',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='trainerservice',
            name='behavioral_issues_addressed',
        ),
        migrations.RemoveField(
            model_name='trainerservice',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='veterinaryclinic',
            name='hours_of_operation',
        ),
        migrations.RemoveField(
            model_name='veterinaryclinic',
            name='photos',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price agreed for the service', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fosterservice',
            name='environment_details',
            field=models.JSONField(default=dict, help_text='Detailed environment information (indoor_space, yard, etc.)'),
        ),
        migrations.RemoveField(
            model_name='fosterservice',
            name='species_accepted',
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booking_type',
            field=models.CharField(choices=[('standard', 'Standard Service'), ('recurring', 'Recurring'), ('emergency', 'Emergency')], default='standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='pets.petprofile'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.serviceprovider'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(help_text='Business email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(help_text='Business phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainerservice',
            name='certifications',
            field=models.JSONField(default=list, help_text="List of professional certifications [{'name': 'CPDT-KA', ...}]"),
        ),
        migrations.RemoveField(
            model_name='trainerservice',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='trainerservice',
            name='species_trained',
        ),
        migrations.RemoveField(
            model_name='veterinaryclinic',
            name='services_offered',
        ),
        migrations.RemoveField(
            model_name='veterinaryclinic',
            name='species_treated',
        ),
        migrations.AddField(
            model_name='businesshours',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory'),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['category', 'verification_status'], name='services_se_categor_f274df_idx'),
        ),
        migrations.AddField(
            model_name='servicemedia',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_options', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceoption'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='service_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceoption'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='fosterservice',
            name='species_accepted',
            field=models.ManyToManyField(related_name='foster_providers', to='services.species'),
        ),
        migrations.AddField(
            model_name='trainerservice',
            name='specializations',
            field=models.ManyToManyField(related_name='trainers', to='services.specialization'),
        ),
        migrations.AddField(
            model_name='trainerservice',
            name='species_trained',
            field=models.ManyToManyField(related_name='trainers', to='services.species'),
        ),
        migrations.AddField(
            model_name='veterinaryclinic',
            name='services_offered',
            field=models.ManyToManyField(related_name='clinics', to='services.serviceoption'),
        ),
        migrations.AddField(
            model_name='veterinaryclinic',
            name='species_treated',
            field=models.ManyToManyField(related_name='clinics', to='services.species'),
        ),
        migrations.AlterUniqueTogether(
            name='businesshours',
            unique_together={('provider', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together={('category', 'name')},
        ),
    ]
