# Generated by Django 5.2.9 on 2026-01-30 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_businesshours_servicecategory_servicemedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon_type', models.CharField(choices=[('salon', 'Salon Based'), ('mobile', 'Mobile Grooming'), ('both', 'Both')], default='salon', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Starting price for basic groom', max_digits=6)),
                ('service_menu', models.JSONField(default=list, help_text="List of services [{'name': 'Full Groom', 'price': 50, 'description': '...'}, ...]")),
                ('amenities', models.JSONField(default=list, help_text="e.g. ['Hypoallergenic Shampoo', 'Cat Friendly']")),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groomer_details', to='services.serviceprovider')),
                ('species_accepted', models.ManyToManyField(related_name='groomers', to='services.species')),
            ],
            options={
                'verbose_name': 'Groomer Service',
                'verbose_name_plural': 'Groomer Services',
            },
        ),
        migrations.CreateModel(
            name='PetSitterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers_dog_walking', models.BooleanField(default=True)),
                ('offers_house_sitting', models.BooleanField(default=False)),
                ('offers_drop_in_visits', models.BooleanField(default=False)),
                ('walking_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('house_sitting_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('drop_in_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('is_insured', models.BooleanField(default=False)),
                ('has_transport', models.BooleanField(default=False)),
                ('service_radius_km', models.IntegerField(default=10, help_text='Service radius in KM')),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sitter_details', to='services.serviceprovider')),
                ('species_accepted', models.ManyToManyField(related_name='sitters', to='services.species')),
            ],
            options={
                'verbose_name': 'Pet Sitter Service',
                'verbose_name_plural': 'Pet Sitter Services',
            },
        ),
    ]
