# Generated by Django 5.2.9 on 2026-01-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_groomerservice_petsitterservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='application_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
