# Generated by Django 5.2.9 on 2026-01-30 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
        ('services', '0005_serviceprovider_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicebooking',
            name='services_se_start_d_39c499_idx',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='start_date',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='booking_date',
            field=models.DateField(default='2024-01-01', help_text='Date of the booking/appointment'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='booking_time',
            field=models.TimeField(blank=True, help_text='Time of appointment (for time-based services)', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='End date and time (for multi-day services)', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='start_datetime',
            field=models.DateTimeField(default='2024-01-01 00:00:00', help_text='Start date and time of service'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['booking_date', 'booking_time'], name='services_se_booking_cf044d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='services_se_start_d_b0cb64_idx'),
        ),
    ]
