# Generated by Django 5.2.9 on 2026-01-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_servicebooking_services_se_start_d_39c499_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereview',
            name='provider_response',
            field=models.TextField(blank=True, help_text="Provider's response to this review", null=True),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='response_date',
            field=models.DateTimeField(blank=True, help_text='When provider responded', null=True),
        ),
    ]
