# Generated by Django 5.2.9 on 2025-12-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, help_text='Display name for the user', max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('photoURL', models.URLField(blank=True, default='https://i.ibb.co.com/hWK4ZpT/petDP.jpg', null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('location_city', models.CharField(blank=True, max_length=100, null=True)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('location_country', models.CharField(default='USA', max_length=100)),
                ('zip_code', models.CharField(blank=True, help_text='Postal code for precise location matching', max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('verified_identity', models.BooleanField(default=False)),
                ('pet_owner_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, help_text='Email verification code', max_length=6, null=True)),
                ('verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verification_code', models.CharField(blank=True, help_text='Phone verification code (SMS)', max_length=6, null=True)),
                ('phone_verification_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='public', max_length=10)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('service_provider', 'Service Provider'), ('user', 'User')], default='user', max_length=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('other', 'Other')], max_length=50)),
                ('own_or_rent', models.CharField(choices=[('own', 'Own'), ('rent', 'Rent')], max_length=10)),
                ('landlord_approval', models.BooleanField(default=False)),
                ('landlord_document', models.FileField(blank=True, null=True, upload_to='verification/landlord/')),
                ('yard_type', models.CharField(blank=True, choices=[('fenced', 'Fenced'), ('unfenced', 'Unfenced'), ('none', 'None')], max_length=50, null=True)),
                ('yard_size', models.CharField(blank=True, max_length=50, null=True)),
                ('num_adults', models.IntegerField(default=1)),
                ('num_children', models.IntegerField(default=0)),
                ('children_ages', models.JSONField(blank=True, default=list)),
                ('current_pets', models.JSONField(blank=True, default=list, help_text='Details of current pets')),
                ('pet_experience', models.JSONField(blank=True, default=dict, help_text='Past ownership experience')),
                ('work_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('hours_away_daily', models.IntegerField(blank=True, null=True)),
                ('activity_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('exercise_commitment', models.IntegerField(blank=True, help_text='Hours/day for exercise', null=True)),
                ('travel_frequency', models.CharField(choices=[('rarely', 'Rarely'), ('monthly', 'Monthly'), ('weekly', 'Weekly')], default='rarely', max_length=50)),
                ('references', models.JSONField(blank=True, default=list)),
                ('veterinarian_reference', models.JSONField(blank=True, null=True)),
                ('why_adopt', models.TextField(help_text='Essay on why adopting')),
                ('readiness_score', models.IntegerField(default=0, help_text='Auto-calculated score (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('service_provider', 'Service Provider'), ('user', 'User')], max_length=20)),
                ('reason', models.TextField(help_text='Reason for requesting this role')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin regarding approval/rejection', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_settings', models.JSONField(blank=True, default=dict)),
                ('verification_badges', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('government_id', 'Government ID'), ('pet_ownership', 'Pet Ownership Proof')], max_length=20)),
                ('document_url', models.URLField(help_text='URL to uploaded document (stored in cloud)', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
