# Generated by Django 5.1.3 on 2025-01-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://i.ibb.co.com/hWK4ZpT/petDP.jpg', null=True),
        ),
    ]
