# Generated by Django 5.1.3 on 2025-12-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_rolerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='aggression_details',
            field=models.TextField(blank=True, help_text='Required if aggression history is True', null=True),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='fun_facts',
            field=models.TextField(blank=True, help_text='Fun facts or quirks about the pet', null=True),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='gotcha_day',
            field=models.DateField(blank=True, help_text='Adoption anniversary', null=True),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='has_aggression_history',
            field=models.BooleanField(default=False, help_text='Mandatory disclosure for safety'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='is_spayed_neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='is_vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='personality_traits',
            field=models.JSONField(blank=True, default=list, help_text='e.g., playful, calm, energetic'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='size',
            field=models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=5, null=True),
        ),
    ]
