# Generated by Django 5.1.3 on 2025-01-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_profile_picture_user_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shelter', 'Shelter'), ('adopter', 'Adopter'), ('guest', 'Guest')], default='guest', max_length=10),
        ),
    ]
