# Generated by Django 5.2.9 on 2026-01-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
