# Generated by Django 5.1.3 on 2025-12-14 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last message')),
                ('archived_by_participant_1', models.BooleanField(default=False)),
                ('archived_by_participant_2', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Message text (5000 char max)', max_length=5000)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('media_url', models.URLField(blank=True, help_text='URL to attached image (optional, 1 photo per message)', max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Has the message been read?')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when message was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_lifted_at', models.DateTimeField(help_text='Auto-set to registration + 30 days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message Restriction',
                'verbose_name_plural': 'Message Restrictions',
            },
        ),
    ]
