# Generated by Django 5.1.3 on 2025-12-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(default='adoption', max_length=20)),
                ('document_url', models.URLField(help_text='URL to generated PDF agreement')),
                ('agreement_template_version', models.CharField(default='1.0', help_text='Track template version for legal compliance', max_length=20)),
                ('terms_text', models.TextField(blank=True, help_text='Snapshot of terms at time of signing')),
                ('pet_owner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('pet_owner_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('adopter_signed_at', models.DateTimeField(blank=True, null=True)),
                ('adopter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Legal Agreement',
                'verbose_name_plural': 'Legal Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve_listing', 'Approve Listing'), ('reject_listing', 'Reject Listing'), ('suspend_user', 'Suspend User'), ('ban_user', 'Ban User'), ('warn_user', 'Warn User'), ('remove_content', 'Remove Content'), ('verify_identity', 'Verify Identity'), ('verify_pet_owner', 'Verify Pet Owner'), ('resolve_report', 'Resolve Report'), ('dismiss_report', 'Dismiss Report')], max_length=30)),
                ('target_content_type', models.CharField(max_length=20)),
                ('target_content_id', models.IntegerField()),
                ('reason', models.TextField(help_text='Public-facing reason for action')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moderation Action',
                'verbose_name_plural': 'Moderation Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('active_users_30d', models.IntegerField(default=0, help_text='Users active in last 30 days')),
                ('total_listings', models.IntegerField(default=0)),
                ('active_listings', models.IntegerField(default=0)),
                ('pending_listings', models.IntegerField(default=0)),
                ('total_adoptions', models.IntegerField(default=0)),
                ('adoptions_this_month', models.IntegerField(default=0)),
                ('adoptions_today', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('pending_applications', models.IntegerField(default=0)),
                ('pending_reports', models.IntegerField(default=0)),
                ('resolved_reports_today', models.IntegerField(default=0)),
                ('messages_sent_today', models.IntegerField(default=0)),
                ('reviews_posted_today', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform Metrics',
                'verbose_name_plural': 'Platform Metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_content_type', models.CharField(help_text='e.g., listing, message, review, profile', max_length=20)),
                ('reported_content_id', models.IntegerField()),
                ('report_type', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('animal_welfare', 'Animal Welfare Concern'), ('misrepresentation', 'Misrepresentation'), ('scam', 'Scam/Fraud')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Auto-calculated from report_type', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
