# Generated by Django 5.1.3 on 2025-12-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalagreement',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_agreement', to='adoption.adoptionapplication'),
        ),
    ]
