# Generated by Django 5.1.3 on 2025-12-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehomingIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(choices=[('moving', 'Moving/Housing Restrictions'), ('allergies', 'Allergies'), ('financial', 'Financial Hardship'), ('time', 'Time Constraints'), ('behavioral', 'Behavioral Issues'), ('health', 'Health Issues (Owner)'), ('too_many', 'Too Many Pets'), ('other', 'Other')], max_length=20)),
                ('reason_text', models.TextField(help_text='Detailed explanation for rehoming (500+ words)')),
                ('urgency_level', models.CharField(choices=[('immediate', 'Immediate'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('flexible', 'Flexible')], max_length=20)),
                ('resources_viewed', models.JSONField(blank=True, default=list, help_text='List of resource types shown')),
                ('cooling_period_end', models.DateTimeField(blank=True, help_text='When the 48-hour cooling period ends (optional)', null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When user acknowledged viewing intervention resources', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rehoming Intervention',
                'verbose_name_plural': 'Rehoming Interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=20)),
                ('admin_feedback', models.TextField(blank=True, help_text='Feedback for the user if changes are requested', null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes for admins', null=True)),
                ('automated_checks', models.JSONField(blank=True, default=dict, help_text='Results of automated quality checks')),
                ('quality_score', models.IntegerField(default=0, help_text='Overall quality score 0-100 based on automated checks')),
                ('red_flags', models.JSONField(blank=True, default=list, help_text='List of red flags detected')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_review', to='pets.rehominglisting')),
            ],
            options={
                'verbose_name': 'Listing Review',
                'verbose_name_plural': 'Listing Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
