# Generated by Django 5.2.9 on 2026-01-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Introductory message to the owner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RehomingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('urgency', models.CharField(max_length=20)),
                ('ideal_home_notes', models.TextField(blank=True)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=50)),
                ('location_zip', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('privacy_level', models.CharField(default='public', max_length=20)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('active', 'Active'), ('paused', 'Paused'), ('under_review', 'Under Review'), ('rehomed', 'Successfully Rehomed'), ('closed', 'Closed')], default='active', max_length=20)),
                ('view_count', models.IntegerField(default=0)),
                ('inquiry_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('rehomed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='RehomingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(default='1.0', max_length=20)),
                ('reason', models.TextField(help_text='Please explain why you need to rehome your pet. This helps us find the best match.')),
                ('urgency', models.CharField(choices=[('immediate', 'Immediate - Emergency'), ('soon', 'Within 1 Month'), ('flexible', 'Flexible Timeline')], max_length=20)),
                ('ideal_home_notes', models.TextField(blank=True, help_text='Describe the ideal new home for your pet')),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=50)),
                ('location_zip', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('privacy_level', models.CharField(choices=[('public', 'Public - Anyone can see'), ('verified', 'Verified Users Only')], default='public', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('cooling_period', 'Cooling Period'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('cooling_period_start', models.DateTimeField(blank=True, null=True)),
                ('cooling_period_end', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_profile_complete', models.BooleanField(default=False)),
                ('pet_profile_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
