# Generated by Django 5.2.9 on 2025-12-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_initial'),
        ('rehoming', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='adopter_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.adopterprofile'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptioncontract',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='rehoming.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='adoptionpayment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rehoming.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='adoptionreview',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rehoming.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='adoptionreview',
            name='reviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_adoption_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_adoption_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postadoptioncheckin',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='rehoming.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='rehomingintervention',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_interventions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rehoming.rehomingintervention'),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='pet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='pet_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehoming_listings', to='pets.petprofile'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='rehoming.rehominglisting'),
        ),
        migrations.AddIndex(
            model_name='adoptioncontract',
            index=models.Index(fields=['is_fully_signed'], name='rehoming_ad_is_full_63c496_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionpayment',
            index=models.Index(fields=['payment_status'], name='rehoming_ad_payment_1f4b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionpayment',
            index=models.Index(fields=['stripe_payment_id'], name='rehoming_ad_stripe__f0b046_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionreview',
            unique_together={('application', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='postadoptioncheckin',
            index=models.Index(fields=['application'], name='rehoming_po_applica_3db675_idx'),
        ),
        migrations.AddIndex(
            model_name='postadoptioncheckin',
            index=models.Index(fields=['check_in_day'], name='rehoming_po_check_i_9a7480_idx'),
        ),
        migrations.AddIndex(
            model_name='rehomingintervention',
            index=models.Index(fields=['user'], name='rehoming_re_user_id_4a2992_idx'),
        ),
        migrations.AddIndex(
            model_name='rehomingintervention',
            index=models.Index(fields=['created_at'], name='rehoming_re_created_92d934_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['pet_owner'], name='rehoming_re_pet_own_e7937c_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['species'], name='rehoming_re_species_f04eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['location_city', 'location_state'], name='rehoming_re_locatio_cf49e9_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['status'], name='rehoming_re_status_569a56_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['-published_at'], name='rehoming_re_publish_1c8803_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['listing'], name='rehoming_ad_listing_94796f_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['applicant'], name='rehoming_ad_applica_51024d_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['status'], name='rehoming_ad_status_650312_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionapplication',
            index=models.Index(fields=['created_at'], name='rehoming_ad_created_f0d288_idx'),
        ),
    ]
