# Generated by Django 5.2.9 on 2026-01-14 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0002_initial'),
        ('rehoming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioninquiry',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_listing', to='pets.petprofile'),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='rehoming.rehominglisting'),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehomingrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_requests', to='pets.petprofile'),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='rehoming.rehomingrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptioninquiry',
            unique_together={('listing', 'requester')},
        ),
        migrations.AddIndex(
            model_name='rehomingrequest',
            index=models.Index(fields=['status', 'created_at'], name='rehoming_re_status_353b75_idx'),
        ),
        migrations.AddIndex(
            model_name='rehomingrequest',
            index=models.Index(fields=['owner', 'status'], name='rehoming_re_owner_i_691fac_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['status', 'urgency'], name='rehoming_re_status_4cf17d_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['location_state', 'status'], name='rehoming_re_locatio_971527_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['published_at'], name='rehoming_re_publish_2777e4_idx'),
        ),
    ]
