# Generated by Django 5.2.9 on 2026-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehomingrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('cooling_period', 'Cooling Period'), ('confirmed', 'Confirmed'), ('listed', 'Listed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
