# Generated by Django 5.2.9 on 2026-01-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0003_alter_rehomingrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehomingrequest',
            name='cooling_period_end',
        ),
        migrations.RemoveField(
            model_name='rehomingrequest',
            name='cooling_period_start',
        ),
        migrations.AlterField(
            model_name='rehomingrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('listed', 'Listed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
