# Generated by Django 5.2.9 on 2026-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0004_remove_rehomingrequest_cooling_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioninquiry',
            name='owner_notes',
            field=models.TextField(blank=True, help_text='Notes from the owner regarding this application', null=True),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection', null=True),
        ),
        migrations.AlterField(
            model_name='adoptioninquiry',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved_meet_greet', 'Approved for Meet & Greet'), ('adopted', 'Adopted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending_review', max_length=50),
        ),
    ]
