# Generated by Django 5.2.9 on 2026-01-28 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0005_adoptioninquiry_owner_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehominglisting',
            name='privacy_level',
        ),
        migrations.RemoveField(
            model_name='rehomingrequest',
            name='privacy_level',
        ),
    ]
