# Generated by Django 5.2.9 on 2026-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehoming', '0006_remove_rehominglisting_privacy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioninquiry',
            name='ai_processed',
            field=models.BooleanField(default=False, help_text='Whether this application has been analyzed by AI'),
        ),
        migrations.AddField(
            model_name='adoptioninquiry',
            name='match_percentage',
            field=models.IntegerField(default=0, help_text='AI Calculated match percentage (0-100)'),
        ),
    ]
