# Generated by Django 5.1.3 on 2025-12-14 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_role', models.CharField(choices=[('pet_owner', 'Pet Owner'), ('adopter', 'Adopter')], max_length=20)),
                ('rating_overall', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('rating_responsiveness', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('rating_preparation', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='For pet owners reviewing adopters', null=True)),
                ('rating_honesty', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='For adopters reviewing pet owners (description accuracy)', null=True)),
                ('rating_communication', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('rating_care_quality', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='For adopters reviewing pet owners (pet care quality)', null=True)),
                ('rating_followthrough', models.IntegerField(blank=True, choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='For pet owners reviewing adopters', null=True)),
                ('review_text', models.TextField(help_text='Detailed review of the adoption experience (200+ chars)')),
                ('would_recommend', models.BooleanField(default=True)),
                ('pet_name', models.CharField(blank=True, help_text='Pet name from application for easy reference', max_length=100)),
                ('review_prompt_sent_at', models.DateTimeField(blank=True, help_text='When review prompt email was sent (7 days after adoption)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='adoption.adoptionapplication')),
            ],
            options={
                'verbose_name': 'Adoption Review',
                'verbose_name_plural': 'Adoption Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
