# Generated by Django 5.1.3 on 2025-01-03 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pet Name')),
                ('species', models.CharField(max_length=50, verbose_name='Species')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Breed')),
                ('age', models.PositiveIntegerField(help_text="Enter pet's age in months", verbose_name='Age (in months)')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (in kg)')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('photo_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Photo URL')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Vaccinated')),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('adopted', 'Adopted')], default='available', max_length=10, verbose_name='Adoption Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='Shelter')),
            ],
        ),
    ]
