# Generated by Django 5.2.9 on 2025-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('rabbit', 'Rabbit'), ('bird', 'Bird'), ('other', 'Other')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, help_text="Pet's birth date", null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in years (if birth date unknown)', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in lbs', max_digits=5, null=True)),
                ('size_category', models.CharField(blank=True, choices=[('xs', 'Extra Small'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xl', 'Extra Large')], max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Short description (500 char max)', max_length=500, null=True)),
                ('photos', models.JSONField(blank=True, default=list, help_text='Array of photo URLs')),
                ('personality_traits', models.JSONField(blank=True, default=list, help_text='e.g., playful, calm, energetic')),
                ('gotcha_day', models.DateField(blank=True, help_text='Adoption anniversary', null=True)),
                ('health_status', models.TextField(blank=True, help_text='Health notes', null=True)),
                ('is_spayed_neutered', models.BooleanField(default=False)),
                ('is_microchipped', models.BooleanField(default=False)),
                ('microchip_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Pet profile status: active, inactive, deceased')),
                ('is_for_rehoming', models.BooleanField(default=False, help_text='Linked to rehoming listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pet Profile',
                'verbose_name_plural': 'Pet Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
