# Generated by Django 5.1.3 on 2025-12-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_url', models.URLField(max_length=500)),
                ('document_type', models.CharField(choices=[('vaccination', 'Vaccination Record'), ('vet_records', 'Veterinary Records'), ('microchip', 'Microchip Registration'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RehomingListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Pet Name')),
                ('species', models.CharField(max_length=50, verbose_name='Species')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Breed')),
                ('birth_date', models.DateField(blank=True, help_text="Pet's birth date for accurate age calculation", null=True)),
                ('age_months', models.PositiveIntegerField(help_text='Age in months if birth date unknown', verbose_name='Age (in months)')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10, verbose_name='Gender')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (in lbs)')),
                ('size', models.CharField(choices=[('xs', 'Extra Small (0-10 lbs)'), ('small', 'Small (11-25 lbs)'), ('medium', 'Medium (26-60 lbs)'), ('large', 'Large (61-100 lbs)'), ('xl', 'Extra Large (100+ lbs)')], default='medium', max_length=15, verbose_name='Size')),
                ('medical_history', models.JSONField(blank=True, default=dict, verbose_name='Medical History')),
                ('behavioral_profile', models.JSONField(blank=True, default=dict, verbose_name='Behavioral Profile')),
                ('aggression_disclosed', models.BooleanField(default=False, help_text='Has aggression been disclosed?')),
                ('aggression_to_people', models.BooleanField(default=False, help_text='Has bitten or injured a person?')),
                ('aggression_to_animals', models.BooleanField(default=False, help_text='Has bitten or injured another animal?')),
                ('aggression_details', models.TextField(blank=True, help_text='Describe any aggression incidents')),
                ('rehoming_story', models.TextField(help_text='Tell us about the pet and why they need a new home (1000+ characters required)', verbose_name='Rehoming Story')),
                ('photos', models.JSONField(default=list, help_text='Array of photo URLs (5 required, 15 max)', verbose_name='Photos')),
                ('watermarked_photos', models.JSONField(blank=True, default=list, help_text='Auto-generated watermarked versions', verbose_name='Watermarked Photos')),
                ('video_url', models.URLField(blank=True, help_text='Optional video (15 sec - 3 min)', max_length=500, null=True, verbose_name='Video URL')),
                ('adoption_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='$0-300 allowed', max_digits=6, verbose_name='Adoption Fee')),
                ('fee_explanation', models.TextField(blank=True, help_text='Required if fee > $0', verbose_name='Fee Explanation')),
                ('included_items', models.JSONField(blank=True, default=list, help_text='Items included with adoption')),
                ('custom_questions', models.JSONField(blank=True, default=list, help_text='Custom screening questions for applicants')),
                ('timeline_adoption_date', models.DateField(blank=True, help_text='Ideal adoption date', null=True, verbose_name='Ideal Adoption Date')),
                ('urgency_level', models.CharField(choices=[('immediate', 'Immediate'), ('1_month', 'Within 1 Month'), ('3_months', 'Within 3 Months'), ('flexible', 'Flexible')], default='flexible', max_length=20, verbose_name='Urgency')),
                ('adopter_experience_required', models.CharField(blank=True, help_text="e.g., 'First-time owner OK', 'Experienced dog owner required'", max_length=50)),
                ('willing_to_stay_in_touch', models.BooleanField(default=True)),
                ('take_back_policy', models.CharField(blank=True, help_text="Will you take the pet back if adoption doesn't work out?", max_length=200)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('location_zip', models.CharField(blank=True, max_length=10)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('service_area_miles', models.IntegerField(default=50, help_text='Service area in miles (999=statewide, 9999=national)')),
                ('hide_exact_address', models.BooleanField(default=True, help_text='Hide address until application approved')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('active', 'Active'), ('on_hold', 'On Hold'), ('adopted', 'Adopted'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20, verbose_name='Listing Status')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection by admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When listing was approved and published', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-set to published_at + 90 days', null=True)),
            ],
            options={
                'verbose_name': 'Rehoming Listing',
                'verbose_name_plural': 'Rehoming Listings',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
