# Generated by Django 5.2.9 on 2026-01-14 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petpersonality',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='pets.petprofile'),
        ),
        migrations.AddField(
            model_name='petmedia',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pets.petprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='petpersonality',
            unique_together={('pet', 'trait')},
        ),
    ]
