# Generated by Django 5.2.9 on 2025-12-21 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='petprofile',
            index=models.Index(fields=['owner'], name='pets_petpro_owner_i_42e3b5_idx'),
        ),
        migrations.AddIndex(
            model_name='petprofile',
            index=models.Index(fields=['species'], name='pets_petpro_species_f23c22_idx'),
        ),
        migrations.AddIndex(
            model_name='petprofile',
            index=models.Index(fields=['is_active'], name='pets_petpro_is_acti_d74d97_idx'),
        ),
        migrations.AddIndex(
            model_name='petprofile',
            index=models.Index(fields=['created_at'], name='pets_petpro_created_839bdd_idx'),
        ),
    ]
