# Generated by Django 5.1.3 on 2025-12-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rehominglisting',
            name='pet_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehoming_listings', to=settings.AUTH_USER_MODEL, verbose_name='Pet Owner'),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='pet_profile',
            field=models.ForeignKey(blank=True, help_text='Link to pet profile, or create inline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehoming_listings', to='users.petprofile'),
        ),
        migrations.AddField(
            model_name='petdocument',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pets.rehominglisting'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['status', '-published_at'], name='pets_rehomi_status_c85fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['species', 'status'], name='pets_rehomi_species_f8fd92_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['location_city', 'location_state'], name='pets_rehomi_locatio_6d09ec_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['adoption_fee'], name='pets_rehomi_adoptio_fab828_idx'),
        ),
        migrations.AddIndex(
            model_name='rehominglisting',
            index=models.Index(fields=['-published_at'], name='pets_rehomi_publish_6d5f81_idx'),
        ),
        migrations.AddConstraint(
            model_name='rehominglisting',
            constraint=models.CheckConstraint(condition=models.Q(('adoption_fee__gte', 0), ('adoption_fee__lte', 300)), name='adoption_fee_range'),
        ),
    ]
