# Generated by Django 5.1.3 on 2025-12-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rehominglisting',
            name='adoption_fee_range',
        ),
        migrations.RemoveIndex(
            model_name='rehominglisting',
            name='pets_rehomi_adoptio_fab828_idx',
        ),
        migrations.RemoveField(
            model_name='rehominglisting',
            name='adoption_fee',
        ),
        migrations.RemoveField(
            model_name='rehominglisting',
            name='fee_explanation',
        ),
    ]
