# Generated by Django 5.1.3 on 2025-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_rehominglisting_adoption_fee_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehominglisting',
            name='adoption_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Adoption fee in USD', max_digits=10),
        ),
        migrations.AddField(
            model_name='rehominglisting',
            name='is_vet_verified',
            field=models.BooleanField(default=False, help_text='Has the pet been verified by a veterinarian?'),
        ),
    ]
